### ISSUE TITLE
raco setup: WARNING: undefined tag (discrete-histogram and discrete-histogram-skip)

### ISSUE THREAD

**Issue by xuchunyang** [alex-hhh/data-frame#2]
`raco pkg install data-frame` prints this warning:

> raco setup: --- building documentation ---                         [5:39:26]
> raco setup: 1 running: <pkgs>/data-frame/scribblings/data-frame.scrbl
> raco setup: WARNING: undefined tag in <pkgs>/data-frame/scribblings/data-frame.scrbl:
> raco setup:  ((lib "plot/no-gui.rkt") discrete-histogram)
> raco setup:  ((lib "plot/utils.rkt") discrete-histogram-skip)
> raco setup: 3 rendering: <pkgs>/data-frame/scribblings/data-frame.scrbl

and on https://docs.racket-lang.org/data-frame/index.html, discrete-histogram and discrete-histogram-skip are not clickable.

**Comment by alex-hhh** [comment]
Unfortunately, my scribble skills are not good enough to fix this error.  You can change the "for-label" require from `plot/no-gui` to `plot` to get rid of one of the missing tag warnings, but the other remains.  You can get rid of both warnings if you remove the `plot/utils` line, but than you'll get a warning about `renderer2d?` not being found.

If you know how to fix this, you are welcome to submit a pull request.

**Comment by xuchunyang** [comment]
This fixes the issue for me, that is, change `plot/utils` to `(only-in plot/utils renderer2d?)`.

```diff
--- /Users/xcy/src/data-frame/scribblings/data-frame.scrbl	2020-02-14 19:25:42.000000000 +0800
+++ data-frame.scrbl	2020-02-14 19:50:10.000000000 +0800
@@ -2,8 +2,8 @@
 @require[@for-label[racket/base
                     racket/contract
                     math/statistics
-                    plot/no-gui
-                    plot/utils
+                    plot
+                    (only-in plot/utils renderer2d?)
                     db]]
 
 @title{data-frame}
@@ -738,7 +738,7 @@
                     
 @defproc[(histogram-renderer (histogram histogram/c)
                              (#:color color any/c #f)
-                             (#:skip real? (discrete-histogram-skip))
+                             (#:skip skip real? (discrete-histogram-skip))
                              (#:x-min x-min real? 0)
                              (#:label label string? #f)
                              (#:blank-some-labels blank-some-labels? boolean? #t)
```

**Comment by alex-hhh** [comment]
Thanks for looking this up.  I pushed a fix.
