### ISSUE TITLE
Additional data-frame constructors

### ISSUE THREAD

**Issue by ralsei** [alex-hhh/data-frame#6]
One of the issues I've had while using `data-frame` is the lack of auxilary constructors for constructing data that is not already read into a CSV, such as data parsed from some API that provides, for example, JSON. `data-frame` provides the `df-read/x` family of functions to construct a data-frame from existing data, but this doesn't exist outside of reading from a file. Mangling your data before it gets into a data-frame isn't particularly easy, currently.

Right now, the workflow looks like:
- turn your data into vectors
- (possibly) sort those vectors
- turn those vectors into series, with names
- (mutably) add all of those series into a new data-frame

or, as I've done a few times:
- open a temporary file
- convert the data to a CSV
- write to that temporary file
- and read it as a data-frame

which is absolutely suboptimal.

Some ideas:
1. Have `make-data-frame` take (optionally) series as arguments, so `(make-data-frame (make-series ...) (make-series ...) ...)` -- this just generally reduces line count for small examples, or when you already have series and don't want to add a `df-add-series` for each individual one
2. Add a `for/data-frame` form, something like:
```racket
#lang racket
(require data-frame
         (for-syntax syntax/for-body))
(provide for/data-frame)

(define-syntax (for/data-frame stx)
  (syntax-case stx ()
    [(_ clauses body ... tail-expr)
     (with-syntax ([original stx]
                   [((pre-body ...) (post-body ...))
                    (split-for-body stx #'(body ... tail-expr))])
       #'(for/fold/derived original
           ([current-df (make-data-frame)])
           clauses
           pre-body ...
           (df-add-series current-df (let () post-body ...))
           current-df))]))

(define df
  (for/data-frame ([name (in-list '("x-var" "y-var"))])
    (make-series name #:data (build-vector (λ (_) (random -50 50))))))
```
but this still requires the `make-series` at the end -- perhaps it could be `values`? But this forgoes comparison functions, et cetera.

Better ideas are obviously welcome.

**Comment by alex-hhh** [comment]
The idea behind the data frame package is that the user would import data from somewhere else and the `make-data-frame` constructor is there only to support writing such import functions.  Currently, data can be imported from a SQL query, a CSV file, but also GPX, TCX, ERG and MRG files (which are somewhat specific to my own interests ...)

So, the various `df-read` functions would be written once and used in lots of situations.  This means that it is not critical to provide many convenience functions to build data frames. Also, given that I have little time to maintain things, I like to keep things simple.

I am open to providing additional constructors for data frames, or improving the existing ones, but I would like to better understand your use case first.  For example, would it not be simpler for you to write a `df-read/json` function?

Also, if you don't need to use temporary files to read CSV data, as `df-read/csv` also works in input ports:

```racket
#lang racket
(require data-frame)
(define df (call-with-input-string
            "\
a,b,c
1,2,3
4,5,6
7,8,9"
 df-read/csv))
```

**Comment by ralsei** [comment]
I'm sorry for not responding to this issue sooner. I've been "busy", I guess?

Basically, I want to make constructing data-frames easier from Racket code, rather than reading from existing data. Take the example of reading performance data from some function into a data-frame, for performance analysis purposes. It would be convenient to iterate and build this row-by-row:
```racket
#lang racket
(require graphite "src/sawzall/for-forms.rkt")

(define (benchmark-function input)
  (sleep input))

(define performance-data
  (for/data-frame (input time)
                  ([v (in-range 5)])
    (define-values (a b tm c) (time-apply benchmark-function (list v)))
    (values v tm)))

(graph #:data performance-data
       #:mapping (aes #:x "input" #:y "time")
       (points))
```
where this `for/data-frame` macro is something I've been using myself for a data-manipulation library that's in the works.

Building a data-frame row-by-row like this is a common enough use-case that it's been included in jackfirth's `rebellion` as the `for/table` form (for a similar data-structure to a data-frame, but less robust). 

I would like to PR this macro (and a similar `for*/data-frame`) into this repo, but I would like your feedback first. Here's the source for them:
<details>
  <summary>source</summary>

```racket
#lang racket/base
(require (for-syntax racket/base
                     syntax/for-body
                     syntax/parse)
         data-frame)
(provide for/data-frame for*/data-frame)

(define (grow-vector vec)
  (define n (vector-length vec))
  (define new-vec (make-vector (* 2 n)))
  (vector-copy! new-vec 0 vec 0 n)
  new-vec)

(define (shrink-vector vec i)
  (define new-vec (make-vector i))
  (vector-copy! new-vec 0 vec 0 i)
  new-vec)

(define (make-df-with-series col-names series)
  (define new-df (make-data-frame))
  (for ([name (in-list col-names)]
        [vec (in-list series)])
    (df-add-series! new-df (make-series name #:data vec)))
  new-df)

(define-for-syntax (for_/data-frame stx for_/fold/derived-stx)
  (syntax-parse stx
    [(_ (column:id ...) clauses body ... tail-expr)
     #:with orig-stx stx
     #:with for_/fold/derived for_/fold/derived-stx
     #:with ((pre-body ...) (post-body ...)) (split-for-body stx #'(body ... tail-expr))
     #'(let ([columns (list (symbol->string 'column) ...)])
         (call-with-values
          (λ ()
            (for_/fold/derived orig-stx
              ([i 0]
               [column (make-vector 16)] ...)
              clauses pre-body ...

              (apply values
                     (add1 i)
                     (for/list ([col-vec (in-list (list column ...))]
                                [value (in-list (call-with-values (λ () post-body ...) list))])
                       (define new-vec (if (eq? i (vector-length col-vec))
                                           (grow-vector col-vec)
                                           col-vec))
                       (vector-set! new-vec i value)
                       new-vec))))
          (λ vecs (make-df-with-series columns
                                       (map (λ (v) (shrink-vector v (car vecs)))
                                            (cdr vecs))))))]))

(define-syntax (for/data-frame stx)
  (for_/data-frame stx #'for/fold/derived))

(define-syntax (for*/data-frame stx)
  (for_/data-frame stx #'for*/fold/derived))
```

</details>

**Comment by alex-hhh** [comment]
If you have been using the `for/data-frame` macro to construct data frames, and found it useful, I will accept a PR for it.  Here are some thoughts of how it should be added to the package:

* I think this should go into a separate file, perhaps "private/for-df.rkt", and included into the package main.rkt file and re-exported, so users have access to it if they just require the data-frame library
* add the LGPL copyright header to the file, see other files for examples (add your name as the copyright holder)
* add some unit tests to "test/df-test.rkt", as a new test suite
* some scribble documentation would be good
* also, it would be good to have some code comments in the source file explaining how this works -- don't assume that this is obvious :-)

**Comment by ralsei** [comment]
Of course I'd do those things for a PR -- this has been a utility macro for myself for the time being. But I'll package up some documentation and submit it. Thanks.
